name: pacapt-tests

on:
  push:
    branches-ignore:
    - no-we-want-to-run-check-on-all-branches

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: prepare
      run: |
        sudo apt-get install libjson-perl liburi-perl

    - name: shellcheck
      run: |
        export CI_SHELLCHECK_UPDATE=yes
        make shellcheck

    - name: shellcheck-POSIX
      run: |
        export CI_SHELLCHECK_UPDATE=yes
        make POSIX

    - name: tests
      run: make tests
